### ISSUE TITLE
add CORS support

### ISSUE THREAD

**Issue by lsloan** [regents-umich-edu/KarpeLiber#8]
# Problem
Michigan Creative wants to use JavaScript, served from a host of their choosing, to query (https://rpi.regents.umich.edu/search).  However, when they do, browsers respond with CORS errors.

Example application, provided by MC developer: https://regents-archive-form.netlify.app/

# Solution
Use the `django-cors-headers` Python module to implement a policy that allows requests from their Netlify-hosted example.

**Comment by sloanlance** [comment]
This has been completed.
